# Generated by Django 2.2.1 on 2019-05-28 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_tweet'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fullname',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
