# Generated by Django 2.2.1 on 2019-06-03 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_feeds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeds',
            name='media',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='feeds',
            name='published',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='feeds',
            name='summary',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
