# Generated by Django 2.2.1 on 2019-05-28 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_user_fullname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profilePic',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
