# Generated by Django 2.2.1 on 2019-06-03 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190603_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeds',
            name='media',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
